export type Difficulty = 'Simple' | 'Intermediate' | 'Hard';

export interface ExamConfig {
  id: string;
  examCode: string;        // 6-char access code generated by server
  subject: string;
  questionCount: number;
  difficulty: Difficulty;
  syllabusText?: string;
  timeLimit: number;       // in minutes
  customQuestions?: string[];
  teacherId: string;
  classroomId: string;
  classroomName: string;
  createdAt: number;
}

export interface StudentAnswer {
  question: string;
  answer: string;
  isCorrect: boolean;
  score: number;           // 0-10
  feedback: string;
}

export interface VivaResponse {
  id: string;
  examId: string;
  examCode: string;
  studentName: string;
  studentEmail: string;
  studentId: string;
  language: string;
  answers: StudentAnswer[];
  grade: number;           // 1-10
  feedback: string;
  logicScore: number;      // 1-10
  timestamp: number;
  timeTaken: number;       // in seconds
  cheatingStrikes?: number;
}

export interface Classroom {
  id: string;
  name: string;
  subject: string;
  teacherId: string;
  teacherName: string;
  createdAt: number;
}

export interface Enrollment {
  id: string;
  classroomId: string;
  studentId: string;
  studentName: string;
  studentEmail: string;
  joinedAt: number;
}

export interface ClassMessage {
  id: string;
  classroomId: string;
  text: string;
  examCode?: string;
  createdAt: number;
}

export interface AnalyticsData {
  subject: string;
  averageGrade: number;
  strugglingCount: number;
  topicHeatmap: { topic: string; score: number }[];
}
